### ISSUE TITLE
Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.flickr.com/services/res...

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#101]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/86001836/

```
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.flickr.com/services/rest/?…
  at getAircraftImage (/drivinandflyin/js/flickr.min.js:1:929)
  at XMLHttpRequest.flightTrackTransferComplete (/drivinandflyin/js/drivinandflyin.js:668:33)
```

**Comment by airmanopus** [comment]
Closing, appears to be duplicate to #99
