### ISSUE TITLE
flightTrackJSON.flightTrack.waypoints is undefined

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#102]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/79731401/

```
TypeError: flightTrackJSON.flightTrack.waypoints is undefined
  at flightTrackTransferComplete (/drivinandflyin/js/drivinandflyin.js:604:13)
  at EventListener.handleEvent*getFlightTrack (/drivinandflyin/js/drivinandflyin.js:529:6)
  at flightStatusTransferComplete (/drivinandflyin/js/drivinandflyin.js:514:7)
  at EventListener.handleEvent*displayFlightDetails (/drivinandflyin/js/drivinandflyin.js:348:4)
  at flightDetails/aircraftPositionRefresh1< (/drivinandflyin/js/drivinandflyin.js:324:3)
...
(5 additional frame(s) were not displayed)
```

**Comment by airmanopus** [comment]
This shouldn't ever happen. (tm). Sentry link doesn't work (wtf?). If we don't get a list of waypoints (we should, as we always ask for the flight plan) there's something wonky. Sentry will (should) pick this up if it happens again.
