### ISSUE TITLE
Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#106]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/86000237/

```
TypeError: Cannot set property 'innerHTML' of null
  at displayFlightDetails (/drivinandflyin/js/drivinandflyin.js:337:50)
  at None (/drivinandflyin/js/drivinandflyin.js:326:5)
  at tick (/drivinandflyin/js/correctingInterval.min.js:1:302)
```

**Comment by airmanopus** [comment]
Closing; this was pointing to a div that likely was munged while I was setting up tabs with bootstrap. It does point out another issue, which is that loading indicators are no longer being displayed (and on mobile they really should be, as it takes a few seconds to load certain data).
