### ISSUE TITLE
Cannot read property 'innerHTML' of null; 403 error trying to access google directions

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#109]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/85990680/

```
TypeError: Cannot read property 'innerHTML' of null
  at showSteps (/drivinandflyin/js/drivinandflyin.js:1131:16)
  at None (/drivinandflyin/js/drivinandflyin.js:1643:9)
  at None (/maps/api/js/DirectionsService.Route:1:28)
```

**Comment by airmanopus** [comment]
This showed up several times in Sentry, but hasn't happened since, so cautiously resolving.
