### ISSUE TITLE
place.geometry.location.lon is not a function

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#117]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/97105936/

```
TypeError: place.geometry.location.lon is not a function
  at updateAirportsCallback (/drivinandflyin/js/drivinandflyin.js:1464:50)
  at _.m.Ig (/maps-api-v3/api/js/23/0/places_impl.js:34:440)
  at None (/maps-api-v3/api/js/23/0/places_impl.js:21:48)
  at null.<anonymous> (/maps-api-v3/api/js/23/0/places_impl.js:9:247)
  at None (/maps-api-v3/api/js/23/0/common.js:46:300)
...
(5 additional frame(s) were not displayed)
```

**Comment by airmanopus** [comment]
Typo. Correct code is
```
var airportLat = place.geometry.location.lat();
 var airportLon = place.geometry.location.lng();
```
