### ISSUE TITLE
Cannot read property '0' of undefined in updateWeather

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#138]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/issues/104555445/

```
TypeError: Cannot read property '0' of undefined
  at updateWeather (/drivinandflyin/js/drivinandflyin.js:236:67)
  at .<anonymous> (/drivinandflyin/js/drivinandflyin.js:98:32)
  at Object._.H.trigger (/maps/api/js:85:121)
  at i_.handleEvent (/maps-api-v3/api/js/23/4/marker.js:50:459)
  at .mf (/maps-api-v3/api/js/23/4/common.js:210:417)
...
(5 additional frame(s) were not displayed)
```

See #130

**Comment by airmanopus** [comment]
Closing as a duplicate to #130
