### ISSUE TITLE
Cannot read property 'reason' of undefined when Google looks for airports and we try to display delays

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#139]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/issues/101278796/

```
TypeError: Cannot read property 'reason' of undefined
  at updateDelays (/drivinandflyin/js/drivinandflyin.js:1467:49)
  at updateAirportsCallback (/drivinandflyin/js/drivinandflyin.js:1808:34)
  at _.t.fh (/maps-api-v3/api/js/23/6/places_impl.js:29:440)
  at None (/maps-api-v3/api/js/23/6/places_impl.js:15:450)
  at .<anonymous> (/maps-api-v3/api/js/23/6/places_impl.js:7:499)
...
(5 additional frame(s) were not displayed)
```

**Comment by airmanopus** [comment]
See https://developers.google.com/maps/documentation/javascript/places
The request we're making returned a 403, which meant that when we tried to use those results to look up airport delays we didn't have valid data to work with
