### ISSUE TITLE
Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.airmanopus.net/cgi-bin/...

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#74]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/67832103/

```
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.airmanopus.net/cgi-bin/air…
  at updateDelays (/drivinandflyin/js/drivinandflyin.js:1070:19)
  at updateAirportsCallback (/drivinandflyin/js/drivinandflyin.js:1470:63)
```

**Comment by airmanopus** [comment]
I haven't been able to duplicate this, leaving open for now just in case.

**Comment by airmanopus** [comment]
Still haven't been able to duplicate; so close #74
