### ISSUE TITLE
Unexpected token s

### ISSUE THREAD

**Issue by airmanopus** [airmanopus/drivinandflyin#88]
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/76172527/

```
SyntaxError: Unexpected token s
  at getFids (/drivinandflyin/js/drivinandflyin.js:181:27)
  at XMLHttpRequest.arrivalsTransferComplete (/drivinandflyin/js/drivinandflyin.js:931:18)
```

**Comment by airmanopus** [comment]
Fixed #89 also

**Comment by airmanopus** [comment]
www.airmanopus.net/:1 Uncaught SyntaxError: Unexpected token s
getFids @ drivinandflyin.js:181
arrivalsTransferComplete @ drivinandflyin.js:931

**Comment by airmanopus** [comment]
The URL we're requesting is borked:

_https://api.flightstats.com/flex/fids/rest/v1/json/MSN/undefined?_

and the *s* is the first letter of the response that we get:

*s*tatus: 404
code: NOT_FOUND
message: Resource not found.

function getFids(airportCode, displayType) was instead
function getFids(airportCode, flightId, displayType)  
(See https://github.com/airmanopus/drivinandflyin/blob/76b551e775affc319b9f1e703a4ec7ca2ece7842/js/drivinandflyin.js)
so of course the parameter in the REST URL was incorrect. 

Resaved and reuploaded js/drivinandflyin.js, cleared cache, and seems to be ok now, but I'm not sure why the several commits old version was loaded (in Chrome).

Same error:
https://app.getsentry.com/steve-noonan-associates/drivin-and-flyin/group/77600318/
